name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error log"
      - run: echo "::warning::This is a warning log"
      - run: echo "::notice::This is a group"
      - run: echo "This is the content of the group"
