name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - uses: actions/checkout@v4
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: helllo
        required: true
        description: A cheeful world
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
