name: Job Summaries
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "## Example :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "This is a summary of the job" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"