name: Sequential Jobs
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the first job"
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - run: echo "This is the second job"
  third:
    runs-on: ubuntu-latest
    needs: second
    steps:
      - run: echo "This is the third job"